// <auto-generated />
namespace MVC_Sample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AppllyDataconverstion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppllyDataconverstion));
        
        string IMigrationMetadata.Id
        {
            get { return "201806021032552_AppllyDataconverstion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
